### ISSUE TITLE
Does not work with angular-mocks 1.5.x

### ISSUE THREAD

**Issue by parliament718** [popduke/angular-mocks-maydelay#4]
may-delay is completely broken with angular-mocks 1.5.x

line 85:  chain.passThrough.apply(chain);

angular-mocke2e-maydelay.js:85  
Uncaught TypeError: Cannot read property 'apply' of undefined

```
      $httpBackend
            .whenGET(...)
            .respond({ ... }, 2000);

        $httpBackend.whenGET(/^\w+.*/).passThrough();
```

**Comment by popduke** [comment]
@parliament718 have a try on v1.0.1 and see if fix your problem

**Comment by amitport** [comment]
v1.0.1 doesn't seem to work with angular 1.5.8

**Comment by popduke** [comment]
@amitport sorry for the late, could you check the new release?
